"""Initial ELA schema with pgvector and FTS."""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table("workspaces", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("slug", sa.String(160), nullable=False, unique=True), sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("users", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("email", sa.String(320), unique=True, nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(30)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("chatbot_settings", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), unique=True), sa.Column("system_prompt", sa.Text()), sa.Column("final_context_top_k", sa.Integer(), server_default="7"), sa.Column("max_context_tokens", sa.Integer(), server_default="10000"), sa.Column("qa_priority_boost", sa.Float(), server_default="1.15"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("documents", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("original_filename", sa.String(255), nullable=False), sa.Column("stored_filename", sa.String(255), nullable=False), sa.Column("mime_type", sa.String(120), nullable=False), sa.Column("file_size", sa.Integer(), nullable=False), sa.Column("content_hash", sa.String(64), nullable=False), sa.Column("status", sa.String(40), server_default="uploaded"), sa.Column("page_count", sa.Integer(), server_default="0"), sa.Column("chunk_count", sa.Integer(), server_default="0"), sa.Column("error_message", sa.Text()), sa.Column("is_active", sa.Boolean(), server_default="true"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("workspace_id", "content_hash", name="uq_documents_workspace_hash"))
    op.create_table("qa_items", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("question", sa.Text(), nullable=False), sa.Column("answer", sa.Text(), nullable=False), sa.Column("category", sa.String(160), server_default="일반"), sa.Column("question_hash", sa.String(64), nullable=False), sa.Column("is_active", sa.Boolean(), server_default="true"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("workspace_id", "question_hash", name="uq_qa_workspace_question"))
    op.create_table("document_chunks", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("document_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False), sa.Column("qa_item_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("qa_items.id", ondelete="CASCADE")), sa.Column("source_type", sa.String(20), server_default="document"), sa.Column("content", sa.Text(), nullable=False), sa.Column("embedding", Vector(1024), nullable=False), sa.Column("search_vector", postgresql.TSVECTOR()), sa.Column("page_number", sa.Integer()), sa.Column("section_title", sa.String(500)), sa.Column("sheet_name", sa.String(255)), sa.Column("row_number", sa.Integer()), sa.Column("token_count", sa.Integer(), nullable=False), sa.Column("chunk_index", sa.Integer(), nullable=False), sa.Column("metadata", postgresql.JSONB(), server_default="{}"), sa.Column("content_hash", sa.String(64)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.execute("CREATE INDEX ix_chunks_embedding_hnsw ON document_chunks USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX ix_chunks_search_vector ON document_chunks USING gin (search_vector)")
    op.execute("CREATE FUNCTION ela_chunks_search_vector() RETURNS trigger AS $$ BEGIN NEW.search_vector := to_tsvector('simple', coalesce(NEW.content, '')); RETURN NEW; END $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER trg_chunks_search_vector BEFORE INSERT OR UPDATE OF content ON document_chunks FOR EACH ROW EXECUTE FUNCTION ela_chunks_search_vector()")
    op.create_table("conversations", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(240)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("messages", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("conversation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False), sa.Column("role", sa.String(20), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("cited_source_ids", postgresql.JSONB(), server_default="[]"), sa.Column("generation_model", sa.String(160)), sa.Column("retrieval_duration_ms", sa.Integer()), sa.Column("generation_duration_ms", sa.Integer()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("ingestion_jobs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("document_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(40), server_default="queued"), sa.Column("stage", sa.String(80), server_default="문서 분석 대기"), sa.Column("progress", sa.Integer(), server_default="0"), sa.Column("error_message", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("retrieval_logs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("question", sa.Text(), nullable=False), sa.Column("normalized_question", sa.Text(), nullable=False), sa.Column("debug_payload", postgresql.JSONB(), server_default="{}"), sa.Column("duration_ms", sa.Integer(), server_default="0"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.execute("INSERT INTO workspaces (id, name, slug) VALUES ('00000000-0000-0000-0000-000000000001', 'ELA Workspace', 'default') ON CONFLICT DO NOTHING")


def downgrade() -> None:
    for table in ["retrieval_logs", "ingestion_jobs", "messages", "conversations", "document_chunks", "qa_items", "documents", "chatbot_settings", "users", "workspaces"]:
        op.drop_table(table)
    op.execute("DROP FUNCTION IF EXISTS ela_chunks_search_vector")
